CREATE INDEX INDEX_ID_CLIENT ON SALE_OF_ABONEMENTS(ID_CLIENT);
DROP INDEX INDEX_ID_CLIENT;

CREATE INDEX INDEX_ID_ABONIMENT ON SALE_OF_ABONEMENTS(ID_ABONEMENT);
DROP INDEX INDEX_ID_ABONIMENT;

SELECT index_name, table_name, column_name
FROM user_ind_columns
WHERE table_name = 'SALE_OF_ABONEMENTS';

CREATE INDEX INDEX_ID_EMPLOYEE ON TIME_TABLE(ID_EMPLOYEE);
DROP INDEX INDEX_ID_EMPLOYEE;

CREATE INDEX INDEX_ID_SERVICES ON TIME_TABLE(ID_SERVICES);
DROP INDEX INDEX_ID_SERVICES;

CREATE INDEX INDEX_ID_TRAINING ON TIME_TABLE(ID_TRAINING);
DROP INDEX INDEX_ID_TRAINING;

SELECT index_name, table_name, column_name
FROM user_ind_columns
WHERE table_name = 'TIME_TABLE';

CREATE INDEX INDEX_SURNAME_CLIENT ON LIST_OF_CLIENTS(SURNAME_CLIENT);
DROP INDEX INDEX_SURNAME_CLIENT;

SELECT index_name, table_name, column_name
FROM user_ind_columns
WHERE table_name = 'LIST_OF_CLIENTS';

CREATE INDEX INDEX_AVAILABILITY_COMPLEXES ON INFO_COMPLEXES(AVAILABILITY_COMPLEXES); --этот не надо
DROP INDEX INDEX_AVAILABILITY_COMPLEXES;

SELECT index_name, table_name, column_name
FROM user_ind_columns
WHERE table_name = 'INFO_COMPLEXES';

CREATE INDEX INDEX_ID_COMPLEXES ON VISIT_RECORD(ID_COMPLEXES);
DROP INDEX INDEX_ID_COMPLEXES;

SELECT index_name, table_name, column_name
FROM user_ind_columns
WHERE table_name = 'VISIT_RECORD';