CREATE PUBLIC SYNONYM LISOFCLI FOR KP_OWNER.LIST_OF_CLIENTS;
DROP SYNONYM LISOFCLI;

SELECT * FROM ALL_SYNONYMS WHERE SYNONYM_NAME = 'LISOFCLI';

CREATE PUBLIC SYNONYM ABONM FOR KP_OWNER.ABONEMENTS;
DROP SYNONYM ABONM;

SELECT * FROM ALL_SYNONYMS WHERE SYNONYM_NAME = 'ABONM';

CREATE PUBLIC SYNONYM SALOFABONM FOR KP_OWNER.SALE_OF_ABONEMENTS;
DROP SYNONYM SALOFABONM;

SELECT * FROM ALL_SYNONYMS WHERE SYNONYM_NAME = 'SALOFABONM';

CREATE PUBLIC SYNONYM INFCOMPL FOR KP_OWNER.INFO_COMPLEXES;
DROP SYNONYM INFCOMPL;

SELECT * FROM ALL_SYNONYMS WHERE SYNONYM_NAME = 'INFCOMPL';

CREATE PUBLIC SYNONYM VISREC FOR KP_OWNER.VISIT_RECORD;
DROP SYNONYM VISREC;

SELECT * FROM ALL_SYNONYMS WHERE SYNONYM_NAME = 'VISREC';

CREATE PUBLIC SYNONYM TIMTAB FOR KP_OWNER.TIME_TABLE;
DROP SYNONYM TIMTAB;

SELECT * FROM ALL_SYNONYMS WHERE SYNONYM_NAME = 'TIMTAB';

CREATE PUBLIC SYNONYM LISOFSERV FOR KP_OWNER.LIST_OF_SERVICES;
DROP SYNONYM LISOFSAL;

SELECT * FROM ALL_SYNONYMS WHERE SYNONYM_NAME = 'LISOFSERV';

CREATE PUBLIC SYNONYM TYPOFTRA FOR KP_OWNER.TYPES_OF_TRAINING;
DROP SYNONYM TYPOFTRA;

SELECT * FROM ALL_SYNONYMS WHERE SYNONYM_NAME = 'TYPOFTRA';

CREATE PUBLIC SYNONYM LISOFEMP FOR KP_OWNER.LIST_OF_EMPLOYEE;
DROP SYNONYM LISOFEMP;

SELECT * FROM ALL_SYNONYMS WHERE SYNONYM_NAME = 'LISOFEMP';