CREATE OR REPLACE PROCEDURE UPDATE_LIST_OF_CLIENTS(pID_CLIENT NUMBER, pSURNAME_CLIENT NVARCHAR2, pNAME_CLIENT NVARCHAR2, pPATRONYMIC_CLIENT NVARCHAR2,
pAGE_CLIENT NUMBER, pADDRESS_CLIENT NVARCHAR2, pTELEPHONE_CLIENT NVARCHAR2, pPASSPORT_CLIENT NVARCHAR2)
IS
BEGIN
    UPDATE LIST_OF_CLIENTS
    SET SURNAME_CLIENT = pSURNAME_CLIENT,
    NAME_CLIENT = pNAME_CLIENT,
    PATRONYMIC_CLIENT = pPATRONYMIC_CLIENT,
    AGE_CLIENT = pAGE_CLIENT,
    ADDRESS_CLIENT = pADDRESS_CLIENT,
    TELEPHONE_CLIENT = pTELEPHONE_CLIENT,
    PASSPORT_CLIENT = pPASSPORT_CLIENT
    WHERE ID_CLIENT = pID_CLIENT;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
                DBMS_OUTPUT.PUT_LINE('Error updating LIST_OF_CLIENTS: ' || SQLERRM);
END;
 
BEGIN
    UPDATE_LIST_OF_CLIENTS(94, 'Кальчевский', 'Даниил', 'Андреевич', 19, 'Минск, ул. Яна Чечота 11-55', '+375445403394', 'MP403049');
END;



CREATE OR REPLACE PROCEDURE UPDATE_ABONEMENTS(pID_ABONEMENT NUMBER, p_TYPE_OF_TRAINING NVARCHAR2, p_TYPE_OF_SERVICE NVARCHAR2, pPRICE NUMBER, pAMOUNT_OF_VISITS NUMBER,
p_AMOUNT_OF_DAYS NUMBER, p_AMOUNT_OF_MONTHS NUMBER)
IS
BEGIN
    UPDATE ABONEMENTS
    SET TYPE_OF_TRAINING = p_TYPE_OF_TRAINING,
    TYPE_OF_SERVICE = p_TYPE_OF_SERVICE,
    PRICE = pPRICE,
    AMOUNT_OF_VISITS = pAMOUNT_OF_VISITS,
    AMOUNT_OF_DAYS = p_AMOUNT_OF_DAYS,
    AMOUNT_OF_MONTHS = p_AMOUNT_OF_MONTHS
    WHERE ID_ABONEMENT = pID_ABONEMENT;
    COMMIT;
       EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
                DBMS_OUTPUT.PUT_LINE('Error updating ABONEMENTS: ' || SQLERRM);
END;
   
BEGIN
     UPDATE_ABONEMENTS(114, 'Аэробика', 'Массаж', 2100, 19, 20, 4);
END;



CREATE OR REPLACE PROCEDURE UPDATE_SALE_OF_ABONEMENTS(pID_SALE NUMBER, pID_CLIENT NUMBER, pID_ABONEMENT NUMBER, pDATA_BEGIN DATE, pDATA_END DATE)
IS
BEGIN
    UPDATE SALE_OF_ABONEMENTS
    SET ID_CLIENT = pID_CLIENT,
    ID_ABONEMENT = pID_ABONEMENT,
    DATA_BEGIN = pDATA_BEGIN,
    DATA_END = pDATA_END
    WHERE ID_SALE = pID_SALE;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
                DBMS_OUTPUT.PUT_LINE('Error updating SALE_OF_ABONEMENTS: ' || SQLERRM);
END;

BEGIN
    UPDATE_SALE_OF_ABONEMENTS(220, 5180, 13653, '08.05.23', '16.09.23');
END;



CREATE OR REPLACE PROCEDURE UPDATE_INFO_COMPLEXES(pID_COMPLEXES NUMBER, pNAME_COMPLEXES NVARCHAR2, pADDRESS_COMPLEXES NVARCHAR2, pCAPACITY_COMPLEXES NUMBER)
IS
BEGIN
    UPDATE INFO_COMPLEXES
    SET NAME_COMPLEXES = pNAME_COMPLEXES,
    ADDRESS_COMPLEXES = pADDRESS_COMPLEXES,
    CAPACITY_COMPLEXES = pCAPACITY_COMPLEXES
    WHERE ID_COMPLEXES = pID_COMPLEXES;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
                DBMS_OUTPUT.PUT_LINE('Error updating INFO_COMPLEXES: ' || SQLERRM);
END;

BEGIN
    UPDATE_INFO_COMPLEXES(84, 'Горе от умв', 'г. Борисов, Борисовская 25', 35);
END;



CREATE OR REPLACE PROCEDURE UPDATE_VISIT_RECORD(pNUMBER_OF_VISITS NUMBER, pID_SALE NUMBER, pNUMBER_RECORD NUMBER, pID_COMPLEXES NUMBER)
IS
BEGIN
    UPDATE VISIT_RECORD
    SET ID_SALE = pID_SALE,
    NUMBER_RECORD = pNUMBER_RECORD,
    ID_COMPLEXES = pID_COMPLEXES
    WHERE NUMBER_OF_VISITS = pNUMBER_OF_VISITS;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
                DBMS_OUTPUT.PUT_LINE('Error updating VISIT_RECORD: ' || SQLERRM);
END;

BEGIN 
    UPDATE_VISIT_RECORD(401, 4900, 100, 55);
END;



CREATE OR REPLACE PROCEDURE UPDATE_TIME_TABLE(pNUMBER_RECORD NUMBER, pDATA_TIME_TABLE DATE, pTIME_BEGIN NVARCHAR2, pTIME_END NVARCHAR2, pID_EMPLOYEE NUMBER,
pID_SERVICES NUMBER, pID_TRAINING NUMBER)
IS
BEGIN
    UPDATE TIME_TABLE
    SET DATA_TIME_TABLE = pDATA_TIME_TABLE,
    TIME_BEGIN = pTIME_BEGIN,
    TIME_END = pTIME_END,
    ID_EMPLOYEE = pID_EMPLOYEE,
    ID_SERVICES = pID_SERVICES,
    ID_TRAINING = pID_TRAINING
    WHERE NUMBER_RECORD = pNUMBER_RECORD;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
                DBMS_OUTPUT.PUT_LINE('Error updating TIME_TABLE: ' || SQLERRM);
END;

BEGIN
    UPDATE_TIME_TABLE(1, '26.06.23', '10:00', '12:00', 30, 95, 75);
END;



CREATE OR REPLACE PROCEDURE UPDATE_LIST_OF_SERVICES(pID_SERVICES NUMBER, pTYPES_OF_SERVICES NVARCHAR2)
IS
BEGIN
    UPDATE LIST_OF_SERVICES
    SET ID_SERVICES = pID_SERVICES,
    TYPES_OF_SERVICES = pTYPES_OF_SERVICES
    WHERE ID_SERVICES = pID_SERVICES;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
                DBMS_OUTPUT.PUT_LINE('Error updating LIST_OF_SERVICES: ' || SQLERRM);
END;

BEGIN
    UPDATE_LIST_OF_SERVICES(3, 'Жим лёжа');
END;



CREATE OR REPLACE PROCEDURE UPDATE_TYPES_OF_TRAINING(pID_TRAINING NUMBER, pTYPES_OF_TRAINING NVARCHAR2)
IS
BEGIN
    UPDATE TYPES_OF_TRAINING
    SET TYPES_OF_TRAINING = pTYPES_OF_TRAINING
    WHERE ID_TRAINING = pID_TRAINING;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
                DBMS_OUTPUT.PUT_LINE('Error updating TYPES_OF_TRAINING: ' || SQLERRM);
END;

BEGIN
    UPDATE_TYPES_OF_TRAINING(5, 'Poles Dance');
END;



CREATE OR REPLACE PROCEDURE UPDATE_LIST_OF_EMPLOYEE(pID_EMPLOYEE NUMBER, pSURNAME_EMPLOYEE NVARCHAR2, pNAME_EMPLOYEE NVARCHAR2, pPATRONYMIC_EMPLOYEE NVARCHAR2,
pTELEPHONE_EMPLOYEE NVARCHAR2, pADDRESS_EMPLOYEE NVARCHAR2, pSALARY_EMPLOYEE NUMBER)
IS
BEGIN
    UPDATE LIST_OF_EMPLOYEE
    SET SURNAME_EMPLOYEE = pSURNAME_EMPLOYEE,
    NAME_EMPLOYEE = pNAME_EMPLOYEE,
    PATRONYMIC_EMPLOYEE = pPATRONYMIC_EMPLOYEE,
    TELEPHONE_EMPLOYEE = pTELEPHONE_EMPLOYEE,
    ADDRESS_EMPLOYEE = pADDRESS_EMPLOYEE,
    SALARY_EMPLOYEE = pSALARY_EMPLOYEE
    WHERE ID_EMPLOYEE = pID_EMPLOYEE;
    COMMIT;
     EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
                DBMS_OUTPUT.PUT_LINE('Error updating LIST_OF_EMPLOYEE: ' || SQLERRM);
END;

BEGIN
    UPDATE_LIST_OF_EMPLOYEE(60, 'Малиновский', 'Андрей', 'Михайлович', '+375296704783', 'г. Рига, Рижская 25-2', 2400);
END;
